[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/_next/static/*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/_next/static/*.css"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "/assets/*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Thu, 31 Dec 2037 23:55:55 GMT"

[[headers]]
  for = "/assets/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Expires = "Thu, 31 Dec 2037 23:55:55 GMT"