const bucketBaseUrl = "https://pugmboivpnkoasgsgfyf.supabase.co/storage/v1/object/public/store-images/FlowerBudsOGDeals";

export const dealsFlowerBuds = [
    { id: 1, budName: "GROOVY GRAPE", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/3-OG-FlowerBud.webp`, bgGradient: "from-blue-500 via-indigo-500 to-purple-500" },
    { id: 2, budName: "PINNACLE", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/4-OG-FlowerBud.webp`, bgGradient: "from-teal-400 via-cyan-500 to-blue-500" },
    { id: 3, budName: "LEMON CHERRY GELATO", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/6-OG-FlowerBud.webp`, bgGradient: "from-yellow-400 via-green-500 to-teal-500" },
    { id: 4, budName: "GELATO PUNCH", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/7-OG-FlowerBud.webp`, bgGradient: "from-pink-500 via-purple-500 to-indigo-500" },
    { id: 5, budName: "ICE CREAM CAKE", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/10-OG-FlowerBud.webp`, bgGradient: "from-pink-400 via-red-500 to-purple-500" },
    { id: 6, budName: "GMO GRAPE", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/11-OG-FlowerBud.webp`, bgGradient: "from-blue-400 via-purple-500 to-pink-500" },
    { id: 7, budName: "OG CHEM", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/12-OG-FlowerBud.webp`, bgGradient: "from-green-500 via-lime-500 to-teal-400" },
    { id: 8, budName: "RS 11", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/13-OG-FlowerBud.webp`, bgGradient: "from-cyan-400 via-blue-500 to-indigo-500" },
    { id: 9, budName: "CAKE & BAKE", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/31-OG-FlowerBud.webp`, bgGradient: "from-pink-500 via-yellow-500 to-orange-400" },
    { id: 10, budName: "**WEDDING CRASHER - INDICA", OneGramPrice: 7.00, FourGramPrice: 24.00, imageSrc: `${bucketBaseUrl}/31-OG-FlowerBud.webp`, bgGradient: "from-pink-500 via-yellow-500 to-orange-400" },
    { id: 11, budName: "TROPICAL CHERRY", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/16-OG-FlowerBud.webp`, bgGradient: "from-teal-500 via-blue-500 to-indigo-500" },
    { id: 12, budName: "PANDEMIC PUNCH", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/19-OG-FlowerBud.webp`, bgGradient: "from-indigo-500 via-purple-400 to-pink-400" },
    { id: 13, budName: "MOONBOW", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/20-OG-FlowerBud.webp`, bgGradient: "from-blue-500 via-cyan-400 to-teal-500" },
    { id: 14, budName: "GUSHERS", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/21-OG-FlowerBud.webp`, bgGradient: "from-yellow-400 via-orange-400 to-red-400" },
    { id: 15, budName: "GELATO 45", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/22-OG-FlowerBud.webp`, bgGradient: "from-cyan-400 via-green-400 to-teal-400" },
    { id: 16, budName: "GUSH MINTZ", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/24-OG-FlowerBud.webp`, bgGradient: "from-green-400 via-teal-400 to-cyan-400" },
    { id: 17, budName: "GLITTER BOMB", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/26-OG-FlowerBud.webp`, bgGradient: "from-green-400 via-yellow-500 to-orange-500" },
    { id: 18, budName: "**SUNDAY RUNTZ - SATIVA** ", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/28-OG-FlowerBud.webp`, bgGradient: "from-green-500 via-teal-500 to-blue-500" },
    { id: 19, budName: "**KUSH MINT - HYBRID**", OneGramPrice: 8.00, FourGramPrice: 28.00, imageSrc: `${bucketBaseUrl}/28-OG-FlowerBud.webp`, bgGradient: "from-green-500 via-teal-500 to-blue-500" },
    { id: 20, budName: "MEAN MAMA", OneGramPrice: 10.00, FourGramPrice: 35.00, imageSrc: `${bucketBaseUrl}/29-OG-FlowerBud.webp`, bgGradient: "from-red-400 via-orange-400 to-yellow-400" },
    { id: 21, budName: "HYBRID HEADBAND", OneGramPrice: 10.00, FourGramPrice: 35.00, imageSrc: `${bucketBaseUrl}/30-OG-FlowerBud.webp`, bgGradient: "from-blue-500 via-cyan-500 to-teal-500" },
];