export const reviews = [
    {
        id: 1,
        name: "Simone Mayfield",
        body: "Come shop here !! Best prices in town. You will not be disappointed ! Great customer service & also very friendly.",
        stars: 5,
        link: "https://g.co/kgs/VJWejdW",
    },
    {
        id: 2,
        name: "Keera e",
        body: "Highly Recommended! One of the best smoke shops in jax. Great customer service. The setup is nice and have everything you need !",
        stars: 5,
        link: "https://g.co/kgs/MXXiDFm",
    },
    {
        id: 3,
        name: "Charia Teston Davis",
        body: "This is hands down the best smoke shop I've ever been to. The owner is such a nice guy and makes everything go smoothly.",
        stars: 5,
        link: "https://g.co/kgs/uxEMppR",
    },
    {
        id: 4,
        name: "Heather Bosswell",
        body: "I love this place. Very friendly and very cooperative. The best smoke shop I've been to!",
        stars: 5,
        link: "https://g.co/kgs/kCTLGEU",
    },
    {
        id: 5,
        name: "Anakë Obliterates",
        body: "Best smoke shop ever. It's my daily for anything I need. Dude who owns/runs it is a great guy.",
        stars: 5,
        link: "https://g.co/kgs/CjpByj9",
    },
    {
        id: 6,
        name: "David M",
        body: "Hands down the best smoke shop in town. They got the best prices and the best customer service you can find!",
        stars: 5,
        link: "https://g.co/kgs/1SnHGcH",
    },
    {
        id: 7,
        name: "Lil Eaz",
        body: "Best prices best customer service plus they sell wine beer best smoke shop on this side of town if you need sweets and treats check us out on DoorDash @koolkiddzwaterice and on instagram best prices in duval.",
        stars: 5,
        link: "https://g.co/kgs/ChSYwms",
    },
    {
        id: 8,
        name: "Audrey Middleton",
        body: "I visit the smoke shop regularly it's well stocked, clean and the owner is so professional and friendly.",
        stars: 5,
        link: "https://g.co/kgs/5G2RhQM",
    },
    {
        id: 9,
        name: "Carrol Crowder",
        body: "Very nice place with good customer service. This smoke shop has everything you need…",
        stars: 5,
        link: "https://g.co/kgs/bdusPdV",
    },
    {
        id: 10,
        name: "Momo Rutledge",
        body: "Great customer service, great products, clean and well stocked! Prices are great. 10/10.",
        stars: 5,
        link: "https://g.co/kgs/17zaNV2",
    },
    {
        id: 11,
        name: "Daniel Horton",
        body: "Owner is a super nice guy very friendly. Love this place. Great prices as well.",
        stars: 5,
        link: "https://g.co/kgs/DGg3BDv",
    },
    {
        id: 12,
        name: "Gag Dag",
        body: "Vibes are always great here and he’s got prices and types for everyone. If you haven’t been here yet, you're missing out.",
        stars: 5,
        link: "https://g.co/kgs/GtcPFPx",
    },
    {
        id: 13,
        name: "Queen Kay",
        body: "LOVE this spot!! Always good vibes and greater prices. Definitely recommend.",
        stars: 5,
        link: "https://g.co/kgs/GVAk8kg",
    },
    {
        id: 14,
        name: "Vaman Patel",
        body: "Great prices! Fun staff. Highly recommend!",
        stars: 5,
        link: "https://g.co/kgs/ThBhbbF",
    },
    {
        id: 15,
        name: "John Doe",
        body: "One of the best shops in the area with good quality gas, 10/10.",
        stars: 5,
        link: "https://g.co/kgs/PLtznNe",
    },
    {
        id: 16,
        name: "Bruce Bennett",
        body: "Very clean and comfortable to walk into. Very professional and everything in the store is affordable.",
        stars: 5,
        link: "https://g.co/kgs/hW9HGEP",
    },
    {
        id: 17,
        name: "Tony Smith",
        body: "Y’all go check out the Inhale Bay Smoke Shop. Never been disappointed.",
        stars: 5,
        link: "https://g.co/kgs/E8zS9Qz",
    },
    {
        id: 18,
        name: "M G",
        body: "Amazing customer service and always an amazing experience coming in.",
        stars: 5,
        link: "https://g.co/kgs/SQGxovd",
    },
    {
        id: 19,
        name: "Eyobe Lemma",
        body: "Good price and clean with good customer service.",
        stars: 5,
        link: "https://g.co/kgs/EoJeVir",
    },
    {
        id: 20,
        name: "Ben Stone",
        body: "Found some great discounts for vapes.",
        stars: 5,
        link: "https://g.co/kgs/htdz2u9",
    },
    {
        id: 21,
        name: "Kennith Robinson",
        body: "Best price for vape.",
        stars: 5,
        link: "https://g.co/kgs/R5e7b92",
    },
    {
        id: 22,
        name: "5avage 2",
        body: "Best smoke shop in town.",
        stars: 5,
        link: "https://g.co/kgs/83J1PDu",
    },
    {
        id: 23,
        name: "Sharray Smith",
        body: "Love this place. HIGHLY RECOMMEND.",
        stars: 5,
        link: "https://g.co/kgs/Dg1c9kz",
    },
    {
        id: 24,
        name: "Gilbert Johnson Johnson",
        body: "Best store in the city.",
        stars: 5,
        link: "https://g.co/kgs/yit8a4s",
    },
    {
        id: 25,
        name: "Jayla Bowman",
        body: "Amazing!!!!",
        stars: 5,
        link: "https://g.co/kgs/Pktaw2T",
    },
    {
        id: 26,
        name: "Phon Nguyen",
        body: "Nice place, good price, enjoy your smoke.",
        stars: 5,
        link: "https://g.co/kgs/12FMPn4",
    },
];